version: '3'

vars:
  BACKEND_DIR: backend
  FRONTEND_DIR: frontend

tasks:
  # ═══════════════════════════════════════════════════
  # Main Commands
  # ═══════════════════════════════════════════════════

  install:
    desc: Install & start full stack (backend + frontend + database)
    cmds:
      - task: _env:setup
      - task: _install:backend
      - task: _install:frontend
      - task: _docker:up:safe
      - echo ""
      - echo "Installation complete!"
      - echo "Backend - http://localhost:8100"
      - echo "Frontend - http://localhost:3000"
      - echo ""
      - echo "Run 'task reset' to reset database with fresh data"

  reset:
    desc: Reset database (drop schema + reseed data)
    cmds:
      - docker-compose exec -T db psql -U retailer -d retailer_db -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;" || echo "WARNING - Database not running. Run task install first."
      - docker-compose exec -T backend python -m app.tools.seed_db
      - echo "Database reset complete!"

  destroy:
    desc: Destroy everything (stop services + remove volumes + clean cache)
    cmds:
      - docker-compose down -v
      - docker system prune -f
      - echo "All services destroyed and cleaned!"

  up:
    desc: Start services (docker-compose up)
    cmds:
      - docker-compose up -d
      - echo "Services started"
      - echo "Backend - http://localhost:8100"
      - echo "Frontend - http://localhost:3000"

  test:
    desc: Run all tests (backend + frontend)
    cmds:
      - task: test:backend
      - task: test:frontend
      - echo ""
      - echo "✓ All tests passed!"

  test:backend:
    desc: Run backend tests with pytest
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - echo "Running backend tests..."
      - docker-compose exec -T backend pytest -v

  test:frontend:
    desc: Run frontend tests with Jest
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - echo "Running frontend tests..."
      - npm test

  test:coverage:
    desc: Run tests with coverage reports
    cmds:
      - task: test:backend:coverage
      - task: test:frontend:coverage
      - echo ""
      - echo "✓ Coverage reports generated!"
      - echo "Backend coverage report at backend/htmlcov/index.html"
      - echo "Frontend coverage report at frontend/coverage/lcov-report/index.html"

  test:backend:coverage:
    desc: Run backend tests with coverage
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - docker-compose exec -T backend pytest --cov=app --cov-report=html --cov-report=term

  test:frontend:coverage:
    desc: Run frontend tests with coverage
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm run test:coverage

  # ═══════════════════════════════════════════════════
  # Internal Tasks (prefixed with _)
  # ═══════════════════════════════════════════════════

  _env:setup:
    desc: Copy .env.example to .env files
    cmds:
      - cp .env.example .env 2>/dev/null || true
      - cp {{.BACKEND_DIR}}/.env.example {{.BACKEND_DIR}}/.env 2>/dev/null || true
    silent: true

  _install:backend:
    desc: Install backend dependencies using uv
    dir: "{{.BACKEND_DIR}}"
    cmds:
      - uv venv
      - uv pip install -r requirements.txt
    silent: true

  _install:frontend:
    desc: Install frontend dependencies using npm
    dir: "{{.FRONTEND_DIR}}"
    cmds:
      - npm install
    silent: true

  _docker:up:safe:
    desc: Start Docker services with retry logic for network resilience
    cmds:
      - docker-compose down 2>/dev/null || true
      - |
        echo "Building & starting services..."
        export DOCKER_BUILDKIT=0
        export COMPOSE_DOCKER_CLI_BUILD=0
        MAX_RETRIES=3
        RETRY=0

        # Rebuild if necessary
        until docker-compose up --build -d || [ $RETRY -eq $MAX_RETRIES ]; do
          RETRY=$((RETRY+1))
          echo "WARNING: Build attempt $RETRY failed. Retrying in 5 seconds..."
          sleep 5
        done
        if [ $RETRY -eq $MAX_RETRIES ]; then
          echo "ERROR: Build failed after $MAX_RETRIES attempts."
          exit 1
        fi
      - echo "Waiting for services to be ready..."
      - sleep 10
      - docker-compose exec -T backend python -m app.tools.seed_db
      - echo "Services started successfully!"
    silent: false
